### ISSUE TITLE
Right content-type

### ISSUE THREAD

**Issue by ehibes** [leonid-shevtsov/s3-browser-upload-demo#2]
Hi,

I cloned your project and everything is working, excepted one thing: content-type on S3. Each uploaded file's content-type is set to binary/octet-stream. How to put correct content-type?

**Comment by leonid-shevtsov** [comment]
Thanks for noticing! I did leave out setting the content-type. I've added it in the latest commit:

https://github.com/leonid-shevtsov/s3-browser-upload-demo/commit/5fcedd5414e38c861fdf4af4cfa7ece7e2a5eb7f

Note that you should set a stricter policy on the content type, based on the requirements.

**Comment by ehibes** [comment]
Another solution is : 
- Update s3UploadPolicy function to accept content-type header
- Just before data.submit add content-type 
```
data.url = s3Data.endpoint_url;
data.formData = s3Data.params;
data.formData['Content-Type'] = data.files[0].type;
data.submit();
```
