### ISSUE TITLE
Do I need a back end?

### ISSUE THREAD

**Issue by chopfitzroy** [leonid-shevtsov/s3-browser-upload-demo#3]
Hey I am new to s3 and I just read your article.

I am working on an electron app and want to do an upload from the front end, however after reading your article this line confused me:

> I found it most convenient to have the backend prepare the entire set of parameters

Does this mean a Node backend is required?

Cheers.

**Comment by GeorgianaPetria** [comment]
Hi @CrashyBang, I'm wondering the same thing. Did you manage to safely upload a file from the front end without a node backend?

**Comment by vlmironoff** [comment]
@GeorgianaPetria @CrashyBang yes the backend is required but only for generating a signature and signing a policy with it. the upload happens from the client when it retrieves a pass from your backend.
The whole reason for having a backend is to secure your aws credentials.

**Comment by leonid-shevtsov** [comment]
You can avoid needing a backend if you can pre-sign a policy that would work for every occasion. So it depends on the use case. If you trust your client (which you most likely _shouldn’t_) you can package the electron app with a permissive pre-signed policy.

**Comment by leonid-shevtsov** [comment]
In any case the backend serves as a gatekeeper between the untrusted client and S3. So you either need a generic presigned policy or a backend.
