### ISSUE TITLE
How to work with folders?

### ISSUE THREAD

**Issue by bangonkali** [leonid-shevtsov/s3-browser-upload-demo#4]
Thanks for this great sample! 

How do i implement uploading directly to folders within a bucket in S3?

**Comment by leonid-shevtsov** [comment]
@bangonkali just prepend the folder name in the `key` argument, here: https://github.com/leonid-shevtsov/s3-browser-upload-demo/blob/master/s3.js#L22 

S3 doesn't really have "folders", it displays folders in the UI if your filenames (or keys, in S3 parlance) have slashes in them.

**Comment by bangonkali** [comment]
On the client side do I need to append anything ?

**Comment by leonid-shevtsov** [comment]
In my implementation, no, because the client uses params constructed on the server.

**Comment by bangonkali** [comment]
Awesome! got it to work.
